export const news = {
    GET_NEWS_REQUEST: "GET_NEWS_REQUEST",
    GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
    GET_NEWS_FAILURE: "GET_NEWS_FAILURE",

    GET_SINGLE_NEW_REQUEST: "GET_SINGLE_NEW_REQUEST",
    GET_SINGLE_NEW_SUCCESS: "GET_SINGLE_NEW_SUCCESS",
    GET_SINGLE_NEW_FAILURE: "GET_SINGLE_NEW_FAILURE",
}
